  apt -y install cmake
  apt -y install libxmlb-dev
  apt -y install sleuthkit
  apt -y install libjcat-dev
  apt -y install gcab
  apt -y install libgcab-dev
  apt -y install libtss2-dev
  apt -y install libcairo2-dev
  apt -y install libefiboot-dev
  apt -y install libsmbios-dev
  apt -y install gnu-efi
  apt -y install libgio2.0-cil-dev
  apt -y install libgirepository1.0-dev
  apt -y install libappstream-glib-dev
  apt -y install mingw-w64-tools
  apt -y install libumockdev-dev
  apt -y install nsis
  apt -y install git
  apt -y install build-essential
  apt -y install vim
  apt -y install fwupd
  apt -y install appstream-util
  apt -y install meson
  apt -y install libglib2.0-dev
  apt -y install libgudev-1.0-dev
  apt -y install gobject-introspection
  apt -y install gtk-doc-tools
  apt -y install libjson-glib-dev
  apt -y install gnutls-bin
  apt -y install libgnutls28-dev
  apt -y install libgpgme-dev
  apt -y install valac
  apt -y install help2man
  apt -y install libusb-1.0-0-dev
  apt -y install sqlite3
  apt -y install libsqlite3-dev
  apt -y install libarchive-dev
  apt -y install libsoup2.4-dev
  apt -y install libpolkit-gobject-1-dev
  apt -y install valgrind
  apt -y install gcab
  apt -y install efivar
  apt -y install libefivar-dev
  apt -y install libelf-dev
  apt -y install libgcab-1.0-0
  apt -y install libtss2-esys0
  apt -y install libgusb-dev
  apt -y install libgcab-1.0-0
  apt -y install d-feet
